name: Dish Craft CI

on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main", "development"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cd into repo
        uses: actions/checkout@v3
        
      - name: set up Java and Maven    
        uses: actions/setup-java@v3 
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: run tests
        working-directory: ./DishCraft

        run: mvn test # Запускаем тесты.
        
  docker-build:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: cd into repo
        uses: actions/checkout@v3
        
      - name: set up Java and Maven    
        uses: actions/setup-java@v3 
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./DishCraft
          file: ./DishCraft/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dishcraft:latest

  render-deploy:
    runs-on: ubuntu-latest
    needs:
      - docker-build
    steps:
      - name: Deploy to production
        uses: bounceapp/render-action@0.6.0
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          render-token: ${{ secrets.MY_RENDER_API_KEY }}
