name: Dish Craft CI

on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main", "development"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cd into repo
        uses: actions/checkout@v3
        
      - name: set up Java and Maven    
        uses: actions/setup-java@v3 
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: run tests
        working-directory: ./DishCraft
        run: mvn test # Запускаем тесты.
